language: java
jdk:
- openjdk7

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false
  hipchat:
    rooms:
      secure: Msnk36RUmuAj4U2wJGTcPV4OdckonlrELCHNu+ShFlQntvQkc05fE7ON8JueIL9iOtOFqciTW2mveZh1qLgxD6BKnF/Opn8feMDMifwDCJJZcFXWQK5e7MNUsOgIDLWmGKZHgZePXgslUGJGStOYzPfA4J3qWPCXuVYUtvIhV5Ne995ZXqXyWbwPGaOknda0gDFQW0+/Iqb0CjS0SnYk0QRIttWjawImSIZJmYFAzVFOAaOfVAXTs20Fpz6bd/bYH7E2F7l/ws4aOqDd0R3Ez0vPc7EFdw6AbgbAa3wt+fC9e16Ea2Z00dVlM9xTZaRDxJh5HhvmImDgumZxurUHKOGtUO5OZ2ydcgjmotxe6U5uY3QYfcATOT+j7VMoxQrTViNiQTFIA20B9HpR1+Z372FivbWqerldxQkutHtUlzGJCGBroFJfBVJg9PhSAPst3zdynzsGncXOmlmT+Nc8dkF4FHj7xzAqgx+rI1B5VNNWOuo6dFccMAPy56r+yNBAfpEhvMqeqkvzTLws2lwav5H2eG+8hAat9jOX5NaKMWtpDnhcARewtql0cb3LUZ6SccQNEp1r9GvMRhZs76jv81zVKMGSy0QTLvgn591CfkF9BswK3F0fiEnCk1Q20as7VwkYRQDOT1Mz9Hwxh+ckippTNMMuoU/Z5GFcYEnIcvE=
    template:
    - 'Build #%{build_number} (%{commit}) of %{repository_name}/%{branch} %{result} (%{duration}) %{build_url}'
